image: gitpod/workspace-node-lts
vscode:
  extensions:
    - eamodio.gitlens
    - https://github.com/bendera/vscode-commit-message-editor/releases/download/v0.19.7/commit-message-editor-0.19.7.vsix
tasks:
  - name: GitHub CLI
    before: echo "Install GitHub CLI (gh)"
    init: echo "No init steps"
    command: .gitpod/scripts/github-cli.sh
  - name: VSCode as Git editor
    before: echo "VSCode will be used as commit and rebase interactive editor"
    init: echo "No init steps"
    command: .gitpod/scripts/vscode-as-git-editor.sh
