name: Deploy on Surge.sh
on:
  push:
    tags:
      - v** # comment this to run on every push for debuggin purposes
jobs:
  build:
      uses: ./.github/workflows/github-actions-demo.yml
<<<<<<< HEAD
      secrets: inherit
=======
<<<<<<< HEAD
      secrets: inherit
=======
>>>>>>> 52c330a603a2659b838ccba2cfceb8c130296001
>>>>>>> e4a283e295370b80e09fc03e42abc28f002b5af5
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{github.ref_name}}-${{ github.sha }}
          path: dist
      - name: List files in the repository
        run: |
          ls -la
          ls -la dist
          cat dist/CHANGELOG.md
      - name: Deploy on Surge.sh
        env:
<<<<<<< HEAD
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        run: npx -yes surge ./dist voiceless-silk.surge.sh
=======
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN  }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN  }}
        run: npx -yes surge ./dist gorgeous-bulb.surge.sh
>>>>>>> e4a283e295370b80e09fc03e42abc28f002b5af5
